baseURL = "https://escuelaramonfdez.org"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "es"
# language code
languageCode = "es"
# language name
languageName = "Español"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

title = "Escuela Ramón Fernández Durán"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  # site description
  description = "La escuela de los movimientos sociales"
  # site keywords
  keywords = ["Escuela", "Movimientos Sociales", "Ecologistas en Acción", "Baladre", "CGT"]
  # date format
  dateFormat = "02-01-2006"
  # website images for Open Graph and Twitter Cards
  images = ["/img/logo.png"]

# Author config
  [params.author]
    name = "Editora"
    email = "escueraramonfdez@riseup.net"
    link = ""

[params.search]
  enable = true
  # type of search engine ("lunr", "algolia")
  type = "lunr"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # LoveIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # LoveIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""

 # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/img/logo.png"
      # title name
      name = "Escuela Ramón Fernández Durán"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # whether to use typeit animation for title name
      typeit = false

# Footer config
[params.footer]
  enable = true
  # Custom content (HTML format is supported)
  custom = ''
  # whether to show Hugo and theme info
  hugo = true
  # whether to show copyright info
  copyright = true
  # whether to show the author
  author = false
  # Site creation time
  since = 2015
  # license info (HTML format is supported)
  license = '<a rel="Licencia Creative Commons Atribución-No comercial-Internacional" href="https://creativecommons.org/licenses/by-nc/4.0/deed.es" target="_blank">CC BY-NC 4.0</a>'

# Home page config
[params.home]
  # Home page profile
  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = "escuelaramonfdez@riseup.net"
    # URL of avatar shown in home page
    avatarURL = "/img/avatar.png"
    # uBlogger CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    title = "Escuela Ramón Fernández Durán"
    # subtitle shown in home page
    subtitle = "La escuela de los Movimientos Sociales"
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
    # whether to use typeit animation for subtitle
    typeit = true
  # Home page posts
  [params.home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
    # uBlogger DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
    # default behavior when you don't set "hiddenFromHomePage" in front matter
    defaultHiddenFromHomePage = false

# Social config about the author
[params.social]
  [params.social.Mastodon]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 0
    # your social ID
    id = "@escuelaramonfdez"
    # prefix of your social link
    prefix = "https://mastodon.social/"
    # content hovering on the icon
    title = "Mastodon"
  [params.social.Facebook]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 1
    # your social ID
    id = "escuela.ramon.fdez.duran"
    # prefix of your social link
    #prefix = ""
    # content hovering on the icon
    title = "Facebook"
  [params.social.GitHub]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 2
    # your social ID
    id = "escuelaramonfdez"
    # prefix of your social link
    #prefix = ""
    # content hovering on the icon
    title = "GitHub"
  [params.social.Email]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 3
    # your social ID
    id = "escuelaramonfdez@riseup.net"
    # prefix of your social link
    #prefix = ""
    # content hovering on the icon
    title = "Email"

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5


[params.page]
  # main subject for articles, by default classic. more on themes}
  theme = "classic"
  # whether to hide a page from home page
  hiddenFromHomePage = false
  # whether to hide a page from search results
  hiddenFromSearch = false
  # Allows you to hide the preview image on the article page
  hiddenFeaturedImage = false
  # whether to enable twemoji
  twemoji = false
  # whether to enable lightgallery
  lightgallery = false
  # whether to enable the ruby extended syntax
  ruby = true
  # whether to enable the fraction extended syntax
  fraction = true
  # whether to enable the fontawesome extended syntax
  fontawesome = true
  # whether to show link to Raw Markdown content of the content
  linkToMarkdown = true
  # whether to show the full text content in RSS
  rssFullText = false
  [params.page.toc]
    # whether to enable the table of the contents
    enable = false
    # whether to keep the static table of the contents in front of the post
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = true
  # social share links in post page
  [params.page.share]
    enable = true
    Whatsapp = true
    Telegram = true
    Facebook = true
    HackerNews = false
    Line = false
    Twitter = false
    Weibo = false
  
  # Mapbox GL JS config
  [params.page.mapbox]
    # access token of Mapbox GL JS
    accessToken = "pk.eyJ1IjoiYXNhbGJlciIsImEiOiJ3bTRrN3JnIn0.zys5YxJbLU-w93nEx5IdEQ"
    # style for the light theme
    lightStyle = "mapbox://styles/mapbox/light-v9"
    # style for the dark theme
    darkStyle = "mapbox://styles/mapbox/dark-v9"
    # whether to add NavigationControl
    navigation = true
    # whether to add GeolocateControl
    geolocate = true
    # whether to add ScaleControl
    scale = true
    # whether to add FullscreenControl
    fullscreen = true
  
  # Third-party library config
  [params.page.library]
    [params.page.library.css]
      # someCSS = "some.css"
      # located in "assets/"
      # Or
      someCSS = "https://fonts.googleapis.com/css?family=Raleway:400,600,700|Open+Sans:300,400,600,700,800|Satisfy:400"
    [params.page.library.js]
      # someJavascript = "some.js"
      # located in "assets/"
      # Or

  [params.page.comment]
    enable = true
    # Disqus comment config
    [params.page.comment.disqus]
      # LoveIt NEW | 0.1.1
      enable = true
      # Disqus shortname to use Disqus in posts
      shortname = "escuelaramonfdezduran"
    # Gitalk comment config
    [params.page.comment.gitalk]
      # LoveIt NEW | 0.1.1
      enable = false
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # Valine comment config
    [params.page.comment.valine]
      enable = false
      appId = ""
      appKey = ""
      placeholder = ""
      avatar = "mp"
      meta= ""
      pageSize = 10
      lang = ""
      visitor = true
      recordIP = true
      highlight = true
      enableQQ = false
      serverURLs = ""


[menu]
  [[menu.main]]
    identifier = "presentacion"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Presentación"
    url = "/presentacion/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "contenidos"
    pre = ""
    post = ""
    name = "Contenidos"
    url = "/contenidos/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "logistica"
    pre = ""
    post = ""
    name = "Logística"
    url = "/logistica/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "inscripcion"
    pre = ""
    post = ""
    name = "Inscripción"
    url = "/inscripcion/"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 5
  [[menu.main]]
    identifier = "historico"
    pre = ""
    post = ""
    name = "Histórico"
    url = "/historico/"
    title = ""
    weight = 6
  [[menu.main]]
    identifier = "contacto"
    pre = ""
    post = ""
    name = "Contacto"
    url = "/contacto"
    title = ""
    weight = 7